language: node_js
node_js:
  - "8"
  - "10"

env:
  DB_DRIVER: mysql
  DB_HOST: 127.0.0.1
  DB_NAME: zxventures
  DB_USER: travis
  DB_PASS:

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE zxventures;'
