language: node_js
node_js:
  - "8"
  - "10"

env:
  DB_DRIVER: mysql
  DB_HOST: 127.0.0.1
  DB_NAME: zxventures
  DB_USER: travis
  DB_PASS:

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE zxventures;'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notification:
  email: false
